cacheFolder: .yarn/cache

compressionLevel: 9

enableGlobalCache: false

enableImmutableInstalls: false

enableStrictSsl: true

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
