nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Railpack compatibility settings
enableGlobalCache: false
enableTelemetry: false
enableStrictSsl: true
networkTimeout: 60000

# Cache configuration for better Railpack integration
cacheFolder: .yarn/cache
compressionLevel: 9
